Server:
  RunMode: debug
  HttpPort: 8088
  ReadTimeout: 60
  WriteTimeout: 60
App:
  Name: oh-admin
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: static/uploads
  UploadImageMaxSize: 5MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
    - .gif
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxx
  Password: xxx
  IsSSL: true
  From: xxx
  To:
    - xxx
JWT:
  Secret: eddycjy
  Issuer: mwq-blog
  Expire: 7200
Database:
  DBType: mysql
  UserName: root
  Password: 123456
  Host: 127.0.0.1:3306
  DBName: oh-admin
  TablePrefix: oh_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Tracer:
  Host: